from __future__ import annotations

AGENT_CAPABILITY_MANIFEST_SCHEMA: dict = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "AgentCapabilityManifest",
    "type": "object",
    "required": [
        "agent_id",
        "agent_name",
        "version",
        "description",
        "supported_input_types",
        "supported_output_types",
        "primary_use_cases",
        "tools_available",
        "mcp_servers",
        "skills_loaded",
        "max_context_tokens",
        "max_response_tokens",
        "max_concurrent_sessions",
        "timeout_seconds",
        "required_env_vars",
        "required_services",
        "min_memory_mb",
        "factory_metadata",
    ],
    "properties": {
        "agent_id": {"type": "string", "minLength": 1},
        "agent_name": {"type": "string", "minLength": 1},
        "version": {"type": "string", "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"},
        "description": {"type": "string"},
        "supported_input_types": {"type": "array", "items": {"type": "string"}},
        "supported_output_types": {"type": "array", "items": {"type": "string"}},
        "primary_use_cases": {"type": "array", "items": {"type": "string"}},
        "tools_available": {"type": "array", "items": {"type": "string"}},
        "mcp_servers": {"type": "array", "items": {"type": "string"}},
        "skills_loaded": {"type": "array", "items": {"type": "string"}},
        "max_context_tokens": {"type": "integer", "minimum": 1},
        "max_response_tokens": {"type": "integer", "minimum": 1},
        "max_concurrent_sessions": {"type": "integer", "minimum": 1},
        "timeout_seconds": {"type": "integer", "minimum": 1},
        "required_env_vars": {"type": "array", "items": {"type": "string"}},
        "required_services": {"type": "array", "items": {"type": "string"}},
        "min_memory_mb": {"type": "integer", "minimum": 64},
        "factory_metadata": {"type": "object"},
    },
    "additionalProperties": False,
}
