from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Optional
import json
import textwrap


class TargetLanguage(str, Enum):
    PYTHON = "python"
    NODEJS = "nodejs"


@dataclass(slots=True)
class DependencyVerificationResult:
    success: bool
    install_logs: str = ""
    error: str | None = None


class LanguageAwarePackager:
    def __init__(self, language: TargetLanguage):
        self.language = language

    def generate_dependency_file(
        self,
        deps: list[str],
        dev_deps: Optional[list[str]] = None,
        output_dir: Path = Path("."),
    ) -> Path:
        if self.language == TargetLanguage.PYTHON:
            return self._write_requirements_txt(deps, output_dir)
        return self._write_package_json(deps, dev_deps or [], output_dir)

    def _write_requirements_txt(self, deps: list[str], output_dir: Path) -> Path:
        content = "\n".join(deps).strip() + "\n"
        path = output_dir / "requirements.txt"
        path.write_text(content, encoding="utf-8")
        return path

    def _write_package_json(
        self,
        deps: list[str],
        dev_deps: list[str],
        output_dir: Path,
        agent_name: str = "generated-agent",
        version: str = "1.0.0",
    ) -> Path:
        def parse_dep(dep_str: str) -> tuple[str, str]:
            if dep_str.startswith("@"):
                parts = dep_str.rsplit("@", 1)
                return parts[0], parts[1] if len(parts) > 1 else "latest"
            parts = dep_str.split("@", 1)
            return parts[0], parts[1] if len(parts) > 1 else "latest"

        pkg = {
            "name": agent_name,
            "version": version,
            "description": "Agent generated by Agent Factory",
            "main": "dist/agent.js",
            "scripts": {
                "start": "node dist/agent.js",
                "build": "tsc",
                "dev": "tsx agent.ts",
                "test": "vitest run",
            },
            "dependencies": {name: f"^{ver}" for name, ver in [parse_dep(d) for d in deps]},
            "devDependencies": {
                name: f"^{ver}" for name, ver in [parse_dep(d) for d in dev_deps]
            },
        }
        path = output_dir / "package.json"
        path.write_text(json.dumps(pkg, indent=2, ensure_ascii=False), encoding="utf-8")
        lock_path = output_dir / "package-lock.json"
        lock_path.write_text(json.dumps({"name": agent_name, "lockfileVersion": 3}, indent=2))
        return path

    def generate_dockerfile(self, output_dir: Path, agent_name: str = "agent") -> Path:
        if self.language == TargetLanguage.PYTHON:
            content = self._python_dockerfile(agent_name)
        else:
            content = self._nodejs_dockerfile(agent_name)
        path = output_dir / "docker" / "Dockerfile"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        compose = output_dir / "docker" / "docker-compose.yml"
        compose.write_text(
            "services:\n  agent:\n    build:\n      context: ..\n      dockerfile: docker/Dockerfile\n"
        )
        return path

    def _python_dockerfile(self, agent_name: str) -> str:
        return textwrap.dedent(
            f"""\
            FROM python:3.12-slim
            WORKDIR /app
            COPY requirements.txt .
            RUN pip install --no-cache-dir -r requirements.txt
            COPY . .
            ENV PYTHONUNBUFFERED=1
            CMD ["python", "{agent_name}.py"]
            """
        )

    def _nodejs_dockerfile(self, agent_name: str) -> str:
        return textwrap.dedent(
            f"""\
            FROM node:20-slim
            WORKDIR /app
            COPY package.json package-lock.json* ./
            RUN npm ci --only=production || npm install --omit=dev
            COPY . .
            RUN npm run build || true
            CMD ["node", "dist/{agent_name}.js"]
            """
        )

    async def verify_dependencies_in_sandbox(
        self, agent_package_dir: Path, timeout_seconds: int = 120
    ) -> DependencyVerificationResult:
        if self.language == TargetLanguage.PYTHON:
            return self._verify_python_deps(agent_package_dir)
        return self._verify_nodejs_deps(agent_package_dir)

    def _verify_python_deps(self, pkg_dir: Path) -> DependencyVerificationResult:
        requirements = pkg_dir / "requirements.txt"
        if not requirements.exists():
            return DependencyVerificationResult(success=False, error="requirements.txt missing")
        lines = [l.strip() for l in requirements.read_text(encoding="utf-8").splitlines() if l.strip()]
        bad = [l for l in lines if "==" not in l]
        if bad:
            return DependencyVerificationResult(
                success=False,
                error=f"unlocked dependency versions: {bad}",
                install_logs="\n".join(lines),
            )
        return DependencyVerificationResult(success=True, install_logs="\n".join(lines))

    def _verify_nodejs_deps(self, pkg_dir: Path) -> DependencyVerificationResult:
        package_json = pkg_dir / "package.json"
        if not package_json.exists():
            return DependencyVerificationResult(success=False, error="package.json missing")
        payload = json.loads(package_json.read_text(encoding="utf-8"))
        deps = payload.get("dependencies", {})
        if not deps:
            return DependencyVerificationResult(
                success=False,
                error="dependencies field is empty",
                install_logs=package_json.read_text(encoding="utf-8"),
            )
        return DependencyVerificationResult(success=True, install_logs=json.dumps(deps, indent=2))

    def generate_quickstart_section(self, agent_name: str, tools_needed: list[str]) -> str:
        env_vars = "\n".join(f"export {tool.upper()}_API_KEY=..." for tool in tools_needed if tool != "none")
        if self.language == TargetLanguage.PYTHON:
            return textwrap.dedent(
                f"""\
                ## Quick Start

                ### 1. Install
                ```bash
                pip install -r requirements.txt
                ```

                ### 2. Configure Env
                ```bash
                cp .env.example .env
                {env_vars if env_vars else "# No external API key required"}
                ```

                ### 3. Run
                ```bash
                python {agent_name}.py
                ```
                """
            )
        return textwrap.dedent(
            f"""\
            ## Quick Start

            ### 1. Install
            ```bash
            npm install
            ```

            ### 2. Configure Env
            ```bash
            cp .env.example .env
            {env_vars if env_vars else "# No external API key required"}
            ```

            ### 3. Run
            ```bash
            npm start
            ```
            """
        )
